import type { Metadata } from "next";
import { Archivo, Poppins } from "next/font/google";
import "./globals.css";
import Header from "./components/Header";
import Footer from "./components/Footer";
import { ClerkProvider } from "@clerk/nextjs";
import { ProfileProvider } from "@/context/ProfileContext";
import AuthWrapper from "./components/AuthWrapper";

const archivo = Archivo({
  variable: "--font-archivo",
  subsets: ["latin"],
});

const poppins = Poppins({
  variable: "--font-poppins",
  weight: ["400", "500", "600", "700"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider>
      <ProfileProvider>
        <html lang="en">
          <body className={`${archivo.variable} ${poppins.variable} antialiased bg-primary`}>
            <AuthWrapper>
              <Header />
              {children}
              <Footer />
            </AuthWrapper>
          </body>
        </html>
      </ProfileProvider>
    </ClerkProvider>
  );
}
